### ISSUE TITLE
FatalErrorException in QueueMonitor.php line 11: syntax error, unexpected '.', expecting ',' or ';'

### ISSUE THREAD

**Issue by djallits** [tremby/laravel-queue-monitor#4]
Discovered in a production env using:
```
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Verified in a development env using:
```
PHP 5.5.38 (cli) (built: Feb 22 2017 10:17:54) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

This is because the Queue Monitor requires `"laravel/framework": "~5.1"` and  Laravel Framework requires `"php": ">=5.5.9"`. I did test and verify the Queue Monitor works when PHP is at least >= 5.6.30

**I haven't devoted time to make a PR, as it appears the developer has a decision to make.**

OPTION 1
Since PHP 5.5 EOL'd on July 21st 2016, the simplest solution would be to either require
`"php": ">=5.6.4",` within your own package. This would allow the package to be installed on Laravel 5.1 or higher as long as it is still on a supported stable version of PHP.

OPTION 2
Bump up the version constraint for the Framework as `"laravel/framework": "~5.3"`.

OPTION 3
Fix the syntax error.

**Comment by tremby** [comment]
Thanks for pointing this out.

Tricky decision!

I think option 2 should be ruled out since Laravel 5.1 is the LTS, and I think it's right to support that.

I don't much like option 3; it'd mean repeating the `queue-monitor:` string (unless you can think of another way), and it's possible (though unlikely) that a user somewhere has extended the class and overridden `CACHE_KEY_PREFIX`, and allowed `QUEUES_CACHE_KEY` to automatically be defined based on that, meaning it's possible it would break someone's code.

So we're left with option 1.
